<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="VictorEspinoza" ignored="0" name="Test" tests="3" failures="1" timestamp="2020-04-29T18:01:48 MDT" time="27.63" errors="0">
  <testcase name="h" time="0.007" classname="com.regression.Flight_Test_Singleton">
    <skipped/>
  </testcase> <!-- h -->
  <testcase name="g" time="0.004" classname="com.regression.Flight_Test_2">
    <failure type="java.lang.AssertionError" message="This method is failed manually">
      <![CDATA[java.lang.AssertionError: This method is failed manually
at com.regression.Flight_Test_2.g(Flight_Test_2.java:26)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- g -->
  <testcase name="f" time="21.453" classname="com.regression.Test_1"/>
</testsuite> <!-- Test -->
